DROP TABLE IF EXISTS TYPING_TEXT;

CREATE TABLE TYPING_TEXT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);