insert into typing_text (title, content) values ('Why is Database Indexing Important?', 'Database indexing improves query performance by allowing the database to quickly locate rows instead of scanning the entire table. An index works like a book\'s table of contents, pointing to the exact location of data. However, too many indexes can slow down write operations, so they should be used strategically.');
insert into typing_text (title, content) values ('What is REST?', 'REST (Representational State Transfer) is a set of principles for designing web APIs that use standard HTTP methods like GET, POST, PUT, and DELETE. It focuses on stateless communication, meaning each request contains all the information needed to process it. RESTful APIs are widely used because they are simple, scalable, and compatible with many platforms.');
insert into typing_text (title, content) values ('What is Caching?', 'Caching stores frequently accessed data temporarily in memory to reduce the time and resources needed to fetch it repeatedly. It improves performance by serving requests faster and reducing the load on databases or external systems. Common caching tools include Redis, Memcached, and browser-based caches for web applications.');

insert into typing_text (title, content) values ('Alice in Wonderland (Lewis Carroll)', 'Alice fell down the rabbit hole and found herself in a strange, whimsical world. Talking creatures, disappearing cats, and curious tea parties surrounded her. Though bewildered, she embraced the adventure. "Curiouser and curiouser," she murmured, stepping further into the unknown.');
insert into typing_text (title, content) values ('The Little Prince (Antoine de Saint-Exupéry)', '"What is essential is invisible to the eye," said the fox to the little prince. As the prince remembered his rose, he understood the value of love and responsibility. He learned that true beauty lies in the time and care we give. His heart grew wiser with each passing moment.');
insert into typing_text (title, content) values ('Peter Pan (J.M. Barrie)', 'Peter Pan taught Wendy and her brothers to fly under the starlit sky. "Think of the happiest things; they\'re the same as having wings!" he exclaimed. Together, they soared to Neverland, where adventure and magic awaited. In that timeless place, they learned the joy of eternal youth.');
insert into typing_text (title, content) values ('The Wizard of Oz (L. Frank Baum)', 'Dorothy clicked her ruby slippers together and whispered, "There\'s no place like home." She had traveled through enchanted lands, befriended unlikely allies, and faced her fears. Yet, she realized the greatest treasure was where her heart belonged. With a whirl of wind, she found herself back in Kansas.');
insert into typing_text (title, content) values ('Cinderella (Charles Perrault)', 'Cinderella\'s glass slipper fit perfectly, proving her identity as the mysterious princess. From ashes to royalty, her kindness and resilience had guided her journey. The prince smiled as he held her hand, promising a future of happiness. Dreams, she thought, really can come true.');
insert into typing_text (title, content) values ('The Jungle Book (Rudyard Kipling)', 'Mowgli roamed the jungle with Baloo, the carefree bear, and Bagheera, the wise panther. "The bare necessities of life will come to you," Baloo sang, reminding Mowgli to enjoy the simple things. Through trials and triumphs, he found where he truly belonged. The jungle was his home.');
insert into typing_text (title, content) values ('Charlotte\'s Web (E.B. White)', '"Some Pig," read the web spun by Charlotte. Wilbur gazed in wonder at the words that saved his life. Charlotte\'s friendship was selfless and unwavering, teaching him the power of loyalty. Even as seasons changed, her memory remained a warm glow in his heart.');
insert into typing_text (title, content) values ('The Snow Queen (Hans Christian Andersen)', 'Gerda braved icy winds and daunting challenges to save her friend, Kai. Guided by her love and determination, she reached the Snow Queen\'s palace. Her tears of warmth melted Kai\'s frozen heart, breaking the spell. Together, they journeyed back to their sunny home.');
insert into typing_text (title, content) values ('Robin Hood (Traditional)', 'Robin Hood and his merry men roamed Sherwood Forest, stealing from the rich to give to the poor. "For justice and fairness!" they cried, standing against tyranny. With wit and bravery, Robin became a hero to the oppressed. His legend lived on in the hearts of the people.');
insert into typing_text (title, content) values ('Beauty and the Beast (Gabrielle-Suzanne Barbot de Villeneuve)', 'Beauty looked past the Beast\'s frightening exterior and saw the kindness within. Her love and understanding broke the spell, revealing a prince. "True beauty," she realized, "lies in the soul." Together, they built a life of harmony and joy.');

